spring:
  application:
    name: eureka-client-newsletter
  profiles:
    active: developer
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      port: 27017
      host: localhost
      database: myCompany
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# choose random port
server:
  port: '${PORT:0}'

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'

# custom config rabbitmq
newsletter:
  rabbitmq:
    exchange: newsletter.exchange
    rountingkey: newsletter.employee.routingkey
    queue: newsletter.queue

# show mongo queries in terminal
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

# custom configuration for firebase
firebase:
  credential-file-name: firebase.json
